name: Release Tag

on:
  workflow_dispatch:
    inputs:
      Upload_to_NuGet:
        description: 'Upload to NuGet'
        default: false
        type: boolean
      Semi_Avalonia:
        description: 'Pack Semi.Avalonia'
        default: true
        type: boolean
      Semi_Avalonia_ColorPicker:
        description: 'Pack Semi.Avalonia.ColorPicker'
        default: true
        type: boolean
      Semi_Avalonia_DataGrid:
        description: 'Pack Semi.Avalonia.DataGrid'
        default: false
        type: boolean
      Semi_Avalonia_TreeDataGrid:
        description: 'Pack Semi.Avalonia.TreeDataGrid'
        default: false
        type: boolean

jobs:
  nuget:
    uses: ./.github/workflows/pack.yml
    with:
      Upload_to_NuGet: ${{ inputs.Upload_to_NuGet }}
      Semi_Avalonia: ${{ inputs.Semi_Avalonia }}
      Semi_Avalonia_ColorPicker: ${{ inputs.Semi_Avalonia_ColorPicker }}
      Semi_Avalonia_DataGrid: ${{ inputs.Semi_Avalonia_DataGrid }}
      Semi_Avalonia_TreeDataGrid: ${{ inputs.Semi_Avalonia_TreeDataGrid }}

  publish:
    uses: ./.github/workflows/publish.yml

  draft-release:
    needs: [ nuget,publish ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4.3.0

      - name: Display structure of downloaded files
        run: ls -R

      - name: Zip artifacts
        run: |
          zip -rj Semi.Avalonia.Demo.Desktop.win-x64.zip Semi.Avalonia.Demo.Desktop.win-x64
          zip -rj Semi.Avalonia.Demo.Desktop.win-x64.NativeAOT.zip Semi.Avalonia.Demo.Desktop.win-x64.NativeAOT
          zip -rj Semi.Avalonia.Demo.Desktop.linux-x64.zip Semi.Avalonia.Demo.Desktop.linux-x64
          zip -rj Semi.Avalonia.Demo.Desktop.linux-x64.NativeAOT.zip Semi.Avalonia.Demo.Desktop.linux-x64.NativeAOT
          zip -rj Semi.Avalonia.Demo.Drm.linux-x64.zip Semi.Avalonia.Demo.Drm.linux-x64
          zip -rj Semi.Avalonia.Demo.Drm.linux-x64.NativeAOT.zip Semi.Avalonia.Demo.Drm.linux-x64.NativeAOT
          zip -rj Semi.Avalonia.Demo.Desktop.osx-arm64.zip Semi.Avalonia.Demo.Desktop.osx-arm64
          cd Semi.Avalonia.Demo.Desktop.osx-arm64.NativeAOT
          zip -r ../Semi.Avalonia.Demo.Desktop.osx-arm64.NativeAOT.zip .

      - name: Display structure of zipped files
        run: ls -R

      - name: Release
        uses: softprops/action-gh-release@v2.3.2
        if: startsWith(github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch'
        with:
          generate_release_notes: true
          draft: true
          files: |
            nugets/*.nupkg
            android-arm64/*.apk
            *.zip